---
# tasks for Application Profile
# VARS: 
#   prechange_file - Filename for ACI changes to be used for Prechange Analysis
#   change_file - Filename for ACI changes to document Change made to ACI
#   tenant - Tenant name
#   ap - Application Profile name
#   description - Application Profile description

- name: Setup APIC Connectivity
  ansible.builtin.set_fact:
    auth: &auth
      host: "{{ ansible_host }}"
      username: "{{ aci_username }}"
      private_key: "{{ aci_private_key }}"
      validate_certs: "{{ aci_validate_certs }}"
      output_path: "{{ prechange_file if ansible_check_mode else change_file }}"

- name: Create AP
  cisco.aci.aci_ap:
    <<: *auth
    tenant: "{{ tenant }}"
    ap: "{{ ap }}"
    description: "{{ description }}"